<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ng nhp bng Googleng nhpTip tc ti matrix_bd4b88</name>
   <tag></tag>
   <elementGuidId>35a9f08f-a04d-40da-a14b-b8ade275d070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.H2SoFe.LZgQXe.TFhTPc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>H2SoFe LZgQXe TFhTPc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-continent</name>
      <type>Main</type>
      <value>Southeast Asia</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-session-region</name>
      <type>Main</type>
      <value>VN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập bằng GoogleĐăng nhậpTiếp tục tới matrix.orgEmail hoặc số điện thoạiBạn quên địa chỉ email?Gõ văn bản bạn nghe hoặc nhìn thấyĐể tiếp tục, Google sẽ chia sẻ tên, địa chỉ email, tùy chọn ngôn ngữ và ảnh hồ sơ của bạn với matrix.org. Trước khi sử dụng matrix.org, bạn có thể xem chính sách quyền riêng tư và điều khoản dịch vụ của ứng dụng này.Tiếp theoTạo tài khoản‪Afrikaans‬‪azərbaycan‬‪bosanski‬‪català‬‪Čeština‬‪Dansk‬‪Deutsch‬‪eesti‬‪English (United Kingdom)‬‪English (United States)‬‪Español (España)‬‪Español (Latinoamérica)‬‪euskara‬‪Filipino‬‪Français (Canada)‬‪Français (France)‬‪galego‬‪Hrvatski‬‪Indonesia‬‪isiZulu‬‪íslenska‬‪Italiano‬‪Kiswahili‬‪latviešu‬‪lietuvių‬‪magyar‬‪Melayu‬‪Nederlands‬‪norsk‬‪polski‬‪Português (Brasil)‬‪Português (Portugal)‬‪română‬‪Slovenčina‬‪slovenščina‬‪srpski (latinica)‬‪Suomi‬‪Svenska‬‪Tiếng Việt‬‪Türkçe‬‪Ελληνικά‬‪български‬‪македонски‬‪монгол‬‪Русский‬‪српски (ћирилица)‬‪Українська‬‪ქართული‬‪հայերեն‬‫עברית‬‎‫اردو‬‎‫العربية‬‎‫فارسی‬‎‪አማርኛ‬‪नेपाली‬‪मराठी‬‪हिन्दी‬‪বাংলা‬‪ਪੰਜਾਬੀ‬‪ગુજરાતી‬‪தமிழ்‬‪తెలుగు‬‪ಕನ್ನಡ‬‪മലയാളം‬‪සිංහල‬‪ไทย‬‪ລາວ‬‪မြန်မာ‬‪ខ្មែរ‬‪한국어‬‪中文（香港）‬‪日本語‬‪简体中文‬‪繁體中文‬Trợ giúpBảo mậtĐiều khoản</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/div[@class=&quot;H2SoFe LZgQXe TFhTPc&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
   </webElementXpaths>
</WebElementEntity>
