<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue (2)</name>
   <tag></tag>
   <elementGuidId>495ecfa9-44b1-4f8e-b2c2-60318100c576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.primary-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Continue')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDJjY2lkIHVzZXJfaWQgPSBAbWluaG5odXRhcHBsZTptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDIwNjc4NjM5MTEKMDAyNmNpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1hcHBsZQowMDJmc2lnbmF0dXJlII6nF0SB-YxZKU9nCn1LQRhe3DPfGJR5v4sVekzQkKLiCg#/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/a[@class=&quot;primary-button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='http://localhost:8080/'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@minhnhutapple:matrix.org'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/main[1]/a[@class=', '&quot;', 'primary-button', '&quot;', ']')])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/?loginToken=MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDJjY2lkIHVzZXJfaWQgPSBAbWluaG5odXRhcHBsZTptYXRyaXgub3JnCjAwMTVjaWQgdHlwZSA9IGxvZ2luCjAwMWRjaWQgdGltZSA8IDE2NDIwNjc4NjM5MTEKMDAyNmNpZCBhdXRoX3Byb3ZpZGVyX2lkID0gb2lkYy1hcHBsZQowMDJmc2lnbmF0dXJlII6nF0SB-YxZKU9nCn1LQRhe3DPfGJR5v4sVekzQkKLiCg#/']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
   </webElementXpaths>
</WebElementEntity>
